export default {
  "version": 6,
  "key": "C",
  "auth": false,
  "siteName": "GlobalGiving",
  "goalList": [],
  "notesPerVisitor": 1,
  "showAbout": false,
  "goalDataHidden": true,
  "effectsRemoved": true,
  "initialGoalGroups": {
    "1": "groupC",
    "2": "groupC",
    "3": "groupC",
    "4": "groupB",
    "6": "groupA",
    "11": "groupA",
    "12": "groupA",
    "(not set)": "groupA"
  },
  "groupA": {
    "groupStr": "groupA",
    "label": "Least Qualified",
    "instrument": "Cello",
    "noteCount": 100,
    "harmonicity": 0,
    "volume": -25,
    "vibratoRate": 4,
    "vibratoAmount": 0.7,
    "voice0": {
      "voice": "voice0",
      "oscillatorType": "square",
      "oscillatorTypePrefix": "fat",
      "oscillatorPartials": 2,
      "modulationType": "sine",
      "modulationIndex": 1,
      "harmonicity": 0,
      "mute": ""
    },
    "voice1": {
      "voice": "voice1",
      "oscillatorType": "sine",
      "oscillatorTypePrefix": "",
      "oscillatorPartials": 2,
      "modulationType": "sine",
      "modulationIndex": 1,
      "harmonicity": 0,
      "mute": false
    },
    "bitcrusherBits": 7,
    "bitcrusherWet": 0.1,
    "chebyshevOrder": 21,
    "chebyshevWet": 0.3,
    "chebyshevOversample": "none",
    "reverbRoomSize": 0.6,
    "reverbWet": 0.5,
    "octave": "2",
    "loops": []
  },
  "groupB": {
    "groupStr": "groupB",
    "label": "Project Pages",
    "instrument": "1st Violins",
    "noteCount": 50,
    "harmonicity": 12,
    "volume": -30,
    "vibratoRate": 3.5,
    "vibratoAmount": 0.4,
    "voice0": {
      "voice": "voice0",
      "oscillatorType": "sine",
      "oscillatorTypePrefix": "fat",
      "oscillatorPartials": 3,
      "modulationType": "sine",
      "modulationIndex": 1,
      "harmonicity": 0,
      "mute": ""
    },
    "voice1": {
      "voice": "voice1",
      "oscillatorType": "square",
      "oscillatorTypePrefix": "",
      "oscillatorPartials": 3,
      "modulationType": "sine",
      "modulationIndex": 1,
      "harmonicity": 0,
      "mute": ""
    },
    "bitcrusherBits": 7,
    "bitcrusherWet": 0.05,
    "chebyshevOrder": 3,
    "chebyshevWet": 0.3,
    "chebyshevOversample": "none",
    "reverbWet": 0.66,
    "reverbRoomSize": 0.6,
    "octave": "3",
    "loops": []
  },
  "groupC": {
    "groupStr": "groupC",
    "label": "Checkout",
    "instrument": "Flute",
    "noteCount": 15,
    "harmonicity": 12,
    "volume": -17,
    "vibratoRate": 6,
    "vibratoAmount": 0.65,
    "voice0": {
      "voice": "voice0",
      "oscillatorType": "square",
      "oscillatorTypePrefix": "",
      "oscillatorPartials": 3,
      "modulationType": "sine",
      "modulationIndex": 1,
      "harmonicity": 0,
      "mute": ""
    },
    "voice1": {
      "voice": "voice1",
      "oscillatorType": "sine",
      "oscillatorTypePrefix": "",
      "oscillatorPartials": 3,
      "modulationType": "sine",
      "modulationIndex": 1,
      "harmonicity": 0,
      "mute": ""
    },
    "bitcrusherBits": 7,
    "bitcrusherWet": 0.05,
    "chebyshevOversample": "none",
    "chebyshevWet": 0.7,
    "chebyshevOrder": 5,
    "reverbWet": 0.8,
    "reverbRoomSize": 0.75,
    "octave": "3",
    "loops": []
  }
}